- name: ansible datatypes
  hosts: local
  connection: local
  vars:
    DURATION: 120 #num
    COURSE: "Devops" #string
    IS_LIVE: true #boolean
    TOOLS: # list
    - Linux
    - Shell
    - ansible
    CONCEPTS: #map or dictionary
      CI: Jenkins
      SCRIPTING: "Shell, Ansible, Terraform, Python"
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Course is: {{ COURSE }}, Duration is {{ DURATION }}, is_live {{ IS_LIVE }}, tools {{ TOOLS }}, Concepts: {{ CONCEPTS }}"