- name: Nginx install and run
  hosts: frontend
  become: yes
  tasks:
  - name: Nginx installation
    ansible.builtin.package:
      name: nginx
      state: present

  - name: start Nginx
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes