- name: Understand vars preferences
  hosts: local
  connection: local
  vars:
    GREETING: "Hello from PLAY"
  vars_files:
  - varinfo.yaml
  vars_prompt:
  - name: GREETING
    prompt: Please enter the GREETING
    private: false
  tasks:
  - name: print the GREETING
    vars:
      GREETING: "Hello from TASK"
    ansible.builtin.debug:
      msg: "{{ GREETING }}"