- name: variable
  hosts: local
  connection: local
  vars:
    NAME: Jyothi
    EMAILID: abc@gmail.com
    ADDRESS: BANGALOOR
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "
#TASK VARS
  - name: print information
    vars:
      NAME: James
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "

  - name: print information
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "

#VARIABLES FROM FILES

- name: variable with file
  hosts: local
  connection: local
  vars_files:
  - varinfo.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{ COURSE }}, Duration is {{ DURATION }}, Trainer is {{ TRAINER }}"

#PROMPT VARIABLES

- name: variables from PROMPT
  hosts: local
  connection: local
  vars_prompt:
  - name: USERNAME
    prompt: please enter your username
    private: false

  - name: PASSWORD
    prompt: please enter your password
    private: true
  tasks:
  - name: printing your information
    ansible.builtin.debug:
      msg: "Hello username is: {{ USERNAME }}, password is: {{  PASSWORD }}"
    
