- name: variable
  hosts: local
  connection: local
  vars:
    NAME: Jyothi
    EMAILID: abc@gmail.com
    ADDRESS: BANGALOOR
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "

  - name: print information
    vars:
      NAME: James
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "

  - name: print information
    ansible.builtin.debug:
      msg: "Name {{ NAME }}, EmailID {{ EMAILID }}, address {{ ADDRESS }} "



- name: variable with file
  hosts: local
  connection: local
  vars_files:
  - varinfo.yaml
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello I am learning {{}}, Duration is {{}}, Trainer is {{}}"